server:
  port: 9000
spring:
#mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.236.62:3306/annoymous-dairy
    username: root
    password: jiezi,./15
#jpa
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    naming:
      strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#thymeleaf
  thymeleaf:
    prefix: classpath:/static/
    mode: LEGACYHTML5
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: Annoymous-dairy-web
#logging
logging:
  file: C:/Users/Jason/Desktop/modules/info.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
        SQL: DEBUG
  pattern:
    file: '[%d{yyyy-MM-dd HH:mm:ss}]-[%-5level]-[%C] - %msg%n'
management:
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/